version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoapp
    depends_on:
      - mongo
    networks:
      - todo-network
    restart: always  

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    networks:
      - todo-network
    restart: always  

  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network
    restart: always
         
volumes:
  mongo-data:

networks:
  todo-network:
